// @flow
export const CREATE_TABLE_BUTTON_CLICK = 'CREATE_TABLE_BUTTON_CLICK';
export const UPDATE_DATA_LIGHT_ARR_VALUE = 'UPDATE_DATA_LIGHT_ARR_VALUE';
export const ADD_PLUS_ONE_IN_CELL = 'ADD_PLUS_ONE_IN_CELL';
export const ADD_ROW_TO_TABLE = 'ADD_ROW_TO_TABLE';
export const DELETE_ROW_TO_TABLE = 'DELETE_ROW_TO_TABLE';
export const PERCENT_ROW_ON = 'PERCENT_ROW_ON';
export const PERCENT_ROW_OFF = 'PERCENT_ROW_OFF';
